//import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/layouts/footer";
//import NavigationMenuDemo from "@/components/layouts/navbar/navbar1";


const inter = Inter({
  subsets: ['latin'],
  variable: "--font-inter",
  display: 'swap'
})


/*
 const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); 
 export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; 
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${inter.variable} antialiased`}
      >
       {/*  <NavigationMenuDemo /> */}
        {children}

        <Footer />
      </body>
    </html>
  );
}
